
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           55686
     no. of nonzeroes in lower triangle of a =          640102
     no. of nonzeroes in the factor l        =         1515790
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            3689
     maximum order of a front matrix         =              90
     maximum size of a front matrix          =            4095
     maximum size of a front trapezoid       =            3270
     METIS reordering method used 
     no. of floating point ops for factor    =      2.7579D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =               0
     number of negative pivots               =               1
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               8
     number of cores used                    =               8
     time (cpu & wall) for structure input   =        0.000000        0.002000
     time (cpu & wall) for ordering          =        1.093750        0.137000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.250000        0.028000
     time (cpu & wall) for numeric factor    =        0.250000        0.037000
     computational rate (gflops) for factor  =        0.110314        0.745367

     no input or output performed

  Total Solver Memory allocated              =       46.594 MB




  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           55686
     no. of nonzeroes in lower triangle of a =          700665
     no. of nonzeroes in the factor l        =         1527931
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            3236
     maximum order of a front matrix         =              90
     maximum size of a front matrix          =            4095
     maximum size of a front trapezoid       =            3192
     METIS reordering method used 
     no. of floating point ops for factor    =      2.8862D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =           55686
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               8
     number of cores used                    =               8
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        524288.        4. MB        512892.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        512892.        4. MB


  Total Solver Memory allocated              =       55.519 MB




  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           55686
     no. of nonzeroes in lower triangle of a =          700665
     no. of nonzeroes in the factor l        =         1527931
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            3236
     maximum order of a front matrix         =              90
     maximum size of a front matrix          =            4095
     maximum size of a front trapezoid       =            3192
     METIS reordering method used 
     no. of floating point ops for factor    =      2.8862D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =           55686
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               8
     number of cores used                    =               8
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        524288.        4. MB        512892.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        512892.        4. MB


  Total Solver Memory allocated              =       55.519 MB




  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           55686
     no. of nonzeroes in lower triangle of a =          700665
     no. of nonzeroes in the factor l        =         1527931
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            3236
     maximum order of a front matrix         =              90
     maximum size of a front matrix          =            4095
     maximum size of a front trapezoid       =            3192
     METIS reordering method used 
     no. of floating point ops for factor    =      2.8862D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =           55686
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               8
     number of cores used                    =               8
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        524288.        4. MB        512892.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        512892.        4. MB


  Total Solver Memory allocated              =       55.519 MB




  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           55686
     no. of nonzeroes in lower triangle of a =          700665
     no. of nonzeroes in the factor l        =         1527931
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            3236
     maximum order of a front matrix         =              90
     maximum size of a front matrix          =            4095
     maximum size of a front trapezoid       =            3192
     METIS reordering method used 
     no. of floating point ops for factor    =      2.8862D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =           55686
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               8
     number of cores used                    =               8
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        524288.        4. MB        512892.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        512892.        4. MB


  Total Solver Memory allocated              =       55.519 MB




  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           55686
     no. of nonzeroes in lower triangle of a =          700665
     no. of nonzeroes in the factor l        =         1527931
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            3236
     maximum order of a front matrix         =              90
     maximum size of a front matrix          =            4095
     maximum size of a front trapezoid       =            3192
     METIS reordering method used 
     no. of floating point ops for factor    =      2.8862D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =           55686
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               8
     number of cores used                    =               8
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        524288.        4. MB        512892.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        512892.        4. MB


  Total Solver Memory allocated              =       55.519 MB




  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           55686
     no. of nonzeroes in lower triangle of a =          700665
     no. of nonzeroes in the factor l        =         1527931
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            3236
     maximum order of a front matrix         =              90
     maximum size of a front matrix          =            4095
     maximum size of a front trapezoid       =            3192
     METIS reordering method used 
     no. of floating point ops for factor    =      2.8862D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =           55686
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               8
     number of cores used                    =               8
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        524288.        4. MB        512892.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        512892.        4. MB


  Total Solver Memory allocated              =       55.519 MB




  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           55686
     no. of nonzeroes in lower triangle of a =          700665
     no. of nonzeroes in the factor l        =         1527931
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =            3236
     maximum order of a front matrix         =              90
     maximum size of a front matrix          =            4095
     maximum size of a front trapezoid       =            3192
     METIS reordering method used 
     no. of floating point ops for factor    =      2.8862D+07
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =           55686
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               8
     number of cores used                    =               8
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        524288.        4. MB        512892.        4. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        512892.        4. MB


  Total Solver Memory allocated              =       55.519 MB
