
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            6342
     no. of nonzeroes in lower triangle of a =           75668
     no. of nonzeroes in the factor l        =          194270
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =             456
     maximum order of a front matrix         =              84
     maximum size of a front matrix          =            3570
     maximum size of a front trapezoid       =            2457
     METIS reordering method used 
     no. of floating point ops for factor    =      4.4333D+06
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =               0
     number of negative pivots               =               1
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =               8
     number of cores used                    =               8
     time (cpu & wall) for structure input   =        0.000000        0.002000
     time (cpu & wall) for ordering          =        0.125000        0.017000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.062500        0.003000

     no input or output performed

  Total Solver Memory allocated              =        5.656 MB
