



  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            6342
     no. of nonzeroes in lower triangle of a =           83865
     no. of nonzeroes in the factor l        =          183475
     ratio of nonzeroes in factor (min/max)  =          0.9855
     number of super nodes                   =             442
     maximum order of a front matrix         =              60
     maximum size of a front matrix          =            1830
     maximum size of a front trapezoid       =            1659
     ParMETIS reordering method used (quality) 
     no. of floating point ops for factor    =      3.6988D+06
     no. of floating point ops for solve     =      4.4207D+06
     ratio of flops for factor (min/max)     =          0.9704
     ratio of allocated memory (max/min)     =          1.0500
     number of positive pivots               =            6342
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     no input or output performed

  Solver Memory allocated on core    0       =        3.511 MB
  Solver Memory allocated on core    1       =        3.344 MB
  Total Solver Memory allocated by all cores =        6.855 MB

