



  Performance statistics for DSP solver: icalls =     42

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            7350
     no. of nonzeroes in lower triangle of a =           96465
     no. of nonzeroes in the factor l        =          208327
     ratio of nonzeroes in factor (min/max)  =          1.0000
     number of super nodes                   =             476
     maximum order of a front matrix         =              72
     maximum size of a front matrix          =            2628
     maximum size of a front trapezoid       =            2328
     METIS reordering method used 
     no. of floating point ops for factor    =      4.1907D+06
     no. of floating point ops for solve     =      0.0000D+00
     ratio of flops for factor (min/max)     =          1.0000
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =            7350
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               1
     number of threads per process used      =              10
     number of cores used                    =              10
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.000000

     no input or output performed

  Total Solver Memory allocated              =        7.590 MB
